/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAnalyticsPopular200,
  GetAnalyticsPopularParams,
  GetAnalyticsStats200,
  PostAnalyticsTrack201,
  PostAnalyticsTrackBody,
} from '../playgroundAPI.schemas';

import { customAxios } from '../../axios-instance';

export const getAnalytics = () => {
  /**
   * Track a page view for analytics (public endpoint)
   * @summary Track page view
   */
  const postAnalyticsTrack = (postAnalyticsTrackBody: PostAnalyticsTrackBody) => {
    return customAxios<PostAnalyticsTrack201>({
      url: `/api/analytics/track`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAnalyticsTrackBody,
    });
  };
  /**
   * Get comprehensive analytics statistics (admin only)
   * @summary Get analytics stats
   */
  const getAnalyticsStats = () => {
    return customAxios<GetAnalyticsStats200>({ url: `/api/analytics/stats`, method: 'GET' });
  };
  /**
   * Get most popular pages based on page views
   * @summary Get popular pages
   */
  const getAnalyticsPopular = (params?: GetAnalyticsPopularParams) => {
    return customAxios<GetAnalyticsPopular200>({ url: `/api/analytics/popular`, method: 'GET', params });
  };
  return { postAnalyticsTrack, getAnalyticsStats, getAnalyticsPopular };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostAnalyticsTrackResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalytics>['postAnalyticsTrack']>>
>;
export type GetAnalyticsStatsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalytics>['getAnalyticsStats']>>
>;
export type GetAnalyticsPopularResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalytics>['getAnalyticsPopular']>>
>;
