/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAuthProfile200,
  PostAuthLogin200,
  PostAuthLoginBody,
  PostAuthLogout200,
  PostAuthRegister201,
  PostAuthRegisterBody,
  PostAuthVerifyCode200,
  PostAuthVerifyCodeBody,
} from '../playgroundAPI.schemas';

import { customAxios } from '../../axios-instance';

export const getAuthentication = () => {
  /**
   * Send a verification code to the specified email address
   * @summary Request verification code
   */
  const postAuthVerifyCode = (postAuthVerifyCodeBody: PostAuthVerifyCodeBody) => {
    return customAxios<PostAuthVerifyCode200>({
      url: `/api/auth/verify-code`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthVerifyCodeBody,
    });
  };
  /**
   * Create a new user account with email verification
   * @summary Register new user
   */
  const postAuthRegister = (postAuthRegisterBody: PostAuthRegisterBody) => {
    return customAxios<PostAuthRegister201>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthRegisterBody,
    });
  };
  /**
   * Authenticate a user with username/email and password
   * @summary User login
   */
  const postAuthLogin = (postAuthLoginBody: PostAuthLoginBody) => {
    return customAxios<PostAuthLogin200>({
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postAuthLoginBody,
    });
  };
  /**
   * Retrieve the authenticated user profile
   * @summary Get current user
   */
  const getAuthProfile = () => {
    return customAxios<GetAuthProfile200>({ url: `/api/auth/me`, method: 'GET' });
  };
  /**
   * Logout the current user (client-side token removal)
   * @summary User logout
   */
  const postAuthLogout = () => {
    return customAxios<PostAuthLogout200>({ url: `/api/auth/logout`, method: 'POST' });
  };
  return { postAuthVerifyCode, postAuthRegister, postAuthLogin, getAuthProfile, postAuthLogout };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PostAuthVerifyCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthentication>['postAuthVerifyCode']>>
>;
export type PostAuthRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthentication>['postAuthRegister']>>
>;
export type PostAuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthentication>['postAuthLogin']>>
>;
export type GetAuthProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthentication>['getAuthProfile']>>
>;
export type PostAuthLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthentication>['postAuthLogout']>>
>;
