/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteFeedDelete200,
  GetFeedList200,
  GetFeedListParams,
  PostFeedCreate201,
  PostFeedCreateBody,
  PostFeedLike200,
} from '../playgroundAPI.schemas';

import { customAxios } from '../../axios-instance';

export const getFeed = () => {
  /**
   * Get all public posts in chronological order
   * @summary Get public feed
   */
  const getFeedList = (params?: GetFeedListParams) => {
    return customAxios<GetFeedList200>({ url: `/api/feed`, method: 'GET', params });
  };
  /**
   * Post a new message to the feed
   * @summary Create post
   */
  const postFeedCreate = (postFeedCreateBody: PostFeedCreateBody) => {
    return customAxios<PostFeedCreate201>({
      url: `/api/feed`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postFeedCreateBody,
    });
  };
  /**
   * Delete your own post (author or admin only)
   * @summary Delete post
   */
  const deleteFeedDelete = (id: string) => {
    return customAxios<DeleteFeedDelete200>({ url: `/api/feed/${id}`, method: 'DELETE' });
  };
  /**
   * Toggle like status on a post
   * @summary Like/unlike post
   */
  const postFeedLike = (id: string) => {
    return customAxios<PostFeedLike200>({ url: `/api/feed/${id}/like`, method: 'POST' });
  };
  return { getFeedList, postFeedCreate, deleteFeedDelete, postFeedLike };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetFeedListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFeed>['getFeedList']>>>;
export type PostFeedCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFeed>['postFeedCreate']>>>;
export type DeleteFeedDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFeed>['deleteFeedDelete']>>>;
export type PostFeedLikeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFeed>['postFeedLike']>>>;
