/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
export type PostAuthVerifyCodeBodyType = (typeof PostAuthVerifyCodeBodyType)[keyof typeof PostAuthVerifyCodeBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthVerifyCodeBodyType = {
  register: 'register',
  reset_password: 'reset_password',
  verify_email: 'verify_email',
} as const;

export type PostAuthVerifyCodeBody = {
  email: string;
  type: PostAuthVerifyCodeBodyType;
};

export type PostAuthVerifyCode200 = {
  message: string;
  dev_code?: string;
};

export type PostAuthVerifyCode400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthVerifyCode409 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthRegisterBody = {
  email: string;
  username: string;
  /** At least 8 characters with uppercase, lowercase, and number */
  password: string;
  /** 6-digit verification code */
  verification_code: string;
  display_name?: string;
};

export type PostAuthRegister201UserRole =
  (typeof PostAuthRegister201UserRole)[keyof typeof PostAuthRegister201UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthRegister201UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type PostAuthRegister201User = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: PostAuthRegister201UserRole;
  email_verified: boolean;
  created_at: number;
};

export type PostAuthRegister201 = {
  access_token: string;
  token_type: string;
  expires_in: number;
  user: PostAuthRegister201User;
};

export type PostAuthRegister400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthRegister409 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthLoginBody = {
  /** Email or username */
  username: string;
  password: string;
};

export type PostAuthLogin200UserRole = (typeof PostAuthLogin200UserRole)[keyof typeof PostAuthLogin200UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthLogin200UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type PostAuthLogin200User = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: PostAuthLogin200UserRole;
  email_verified: boolean;
  created_at: number;
};

export type PostAuthLogin200 = {
  access_token: string;
  token_type: string;
  expires_in: number;
  user: PostAuthLogin200User;
};

export type PostAuthLogin401 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthLogin403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type GetAuthProfile200Role = (typeof GetAuthProfile200Role)[keyof typeof GetAuthProfile200Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuthProfile200Role = {
  admin: 'admin',
  user: 'user',
} as const;

export type GetAuthProfile200 = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: GetAuthProfile200Role;
  email_verified: boolean;
  created_at: number;
};

export type GetAuthProfile401 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAuthLogout200 = {
  message: string;
};

export type GetCommentsListParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetCommentsList200ItemsItemParentId = string | null;

export type GetCommentsList200ItemsItemStatus =
  (typeof GetCommentsList200ItemsItemStatus)[keyof typeof GetCommentsList200ItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCommentsList200ItemsItemStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export type GetCommentsList200ItemsItemUserRole =
  (typeof GetCommentsList200ItemsItemUserRole)[keyof typeof GetCommentsList200ItemsItemUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCommentsList200ItemsItemUserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type GetCommentsList200ItemsItemUser = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: GetCommentsList200ItemsItemUserRole;
  email_verified: boolean;
  created_at: number;
};

export type GetCommentsList200ItemsItem = {
  id: string;
  post_slug: string;
  user_id: string;
  parent_id: GetCommentsList200ItemsItemParentId;
  content: string;
  status: GetCommentsList200ItemsItemStatus;
  likes_count: number;
  created_at: number;
  updated_at: number;
  user: GetCommentsList200ItemsItemUser;
  replies?: unknown[];
  is_liked?: boolean;
};

export type GetCommentsList200 = {
  items: GetCommentsList200ItemsItem[];
  total: number;
  page: number;
  limit: number;
  has_more: boolean;
};

export type PostCommentsCreateBody = {
  post_slug: string;
  /** Comment content (max 2000 characters) */
  content: string;
  /** Parent comment ID for replies */
  parent_id?: string;
};

export type PostCommentsCreate201ParentId = string | null;

export type PostCommentsCreate201Status =
  (typeof PostCommentsCreate201Status)[keyof typeof PostCommentsCreate201Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCommentsCreate201Status = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export type PostCommentsCreate201UserRole =
  (typeof PostCommentsCreate201UserRole)[keyof typeof PostCommentsCreate201UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCommentsCreate201UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type PostCommentsCreate201User = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: PostCommentsCreate201UserRole;
  email_verified: boolean;
  created_at: number;
};

export type PostCommentsCreate201 = {
  id: string;
  post_slug: string;
  user_id: string;
  parent_id: PostCommentsCreate201ParentId;
  content: string;
  status: PostCommentsCreate201Status;
  likes_count: number;
  created_at: number;
  updated_at: number;
  user: PostCommentsCreate201User;
  replies?: unknown[];
  is_liked?: boolean;
};

export type PostCommentsCreate400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostCommentsCreate401 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PutCommentsUpdateBody = {
  /** Updated comment content */
  content: string;
};

export type PutCommentsUpdate200ParentId = string | null;

export type PutCommentsUpdate200Status = (typeof PutCommentsUpdate200Status)[keyof typeof PutCommentsUpdate200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCommentsUpdate200Status = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export type PutCommentsUpdate200UserRole =
  (typeof PutCommentsUpdate200UserRole)[keyof typeof PutCommentsUpdate200UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCommentsUpdate200UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type PutCommentsUpdate200User = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: PutCommentsUpdate200UserRole;
  email_verified: boolean;
  created_at: number;
};

export type PutCommentsUpdate200 = {
  id: string;
  post_slug: string;
  user_id: string;
  parent_id: PutCommentsUpdate200ParentId;
  content: string;
  status: PutCommentsUpdate200Status;
  likes_count: number;
  created_at: number;
  updated_at: number;
  user: PutCommentsUpdate200User;
  replies?: unknown[];
  is_liked?: boolean;
};

export type PutCommentsUpdate400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PutCommentsUpdate403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PutCommentsUpdate404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type DeleteCommentsDelete200 = {
  message: string;
};

export type DeleteCommentsDelete403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type DeleteCommentsDelete404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostCommentsLike200 = {
  liked: boolean;
  message: string;
};

export type PostCommentsLike404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type GetFeedListParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetFeedList200ItemsItemImages = string | null;

export type GetFeedList200ItemsItemVisibility =
  (typeof GetFeedList200ItemsItemVisibility)[keyof typeof GetFeedList200ItemsItemVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFeedList200ItemsItemVisibility = {
  public: 'public',
  private: 'private',
} as const;

export type GetFeedList200ItemsItemUserRole =
  (typeof GetFeedList200ItemsItemUserRole)[keyof typeof GetFeedList200ItemsItemUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFeedList200ItemsItemUserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type GetFeedList200ItemsItemUser = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: GetFeedList200ItemsItemUserRole;
  email_verified: boolean;
  created_at: number;
};

export type GetFeedList200ItemsItem = {
  id: string;
  user_id: string;
  content: string;
  images: GetFeedList200ItemsItemImages;
  visibility: GetFeedList200ItemsItemVisibility;
  likes_count: number;
  comments_count: number;
  created_at: number;
  updated_at: number;
  user: GetFeedList200ItemsItemUser;
  images_array: string[];
  is_liked?: boolean;
};

export type GetFeedList200 = {
  items: GetFeedList200ItemsItem[];
  total: number;
  page: number;
  limit: number;
  has_more: boolean;
};

export type PostFeedCreateBodyVisibility =
  (typeof PostFeedCreateBodyVisibility)[keyof typeof PostFeedCreateBodyVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostFeedCreateBodyVisibility = {
  public: 'public',
  private: 'private',
} as const;

export type PostFeedCreateBody = {
  /** Post content (max 2000 characters) */
  content: string;
  images?: string[];
  visibility?: PostFeedCreateBodyVisibility;
};

export type PostFeedCreate201Images = string | null;

export type PostFeedCreate201Visibility =
  (typeof PostFeedCreate201Visibility)[keyof typeof PostFeedCreate201Visibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostFeedCreate201Visibility = {
  public: 'public',
  private: 'private',
} as const;

export type PostFeedCreate201UserRole = (typeof PostFeedCreate201UserRole)[keyof typeof PostFeedCreate201UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostFeedCreate201UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export type PostFeedCreate201User = {
  id: string;
  email: string;
  username: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  role: PostFeedCreate201UserRole;
  email_verified: boolean;
  created_at: number;
};

export type PostFeedCreate201 = {
  id: string;
  user_id: string;
  content: string;
  images: PostFeedCreate201Images;
  visibility: PostFeedCreate201Visibility;
  likes_count: number;
  comments_count: number;
  created_at: number;
  updated_at: number;
  user: PostFeedCreate201User;
  images_array: string[];
  is_liked?: boolean;
};

export type PostFeedCreate400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostFeedCreate401 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type DeleteFeedDelete200 = {
  message: string;
};

export type DeleteFeedDelete403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type DeleteFeedDelete404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostFeedLike200 = {
  liked: boolean;
  message: string;
};

export type PostFeedLike404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PostAnalyticsTrackBody = {
  path: string;
  referrer?: string;
};

export type PostAnalyticsTrack201 = {
  message: string;
};

export type GetAnalyticsStats200PopularPagesItem = {
  path: string;
  views: number;
};

export type GetAnalyticsStats200DailyStatsItem = {
  date: string;
  views: number;
  unique_visitors: number;
};

export type GetAnalyticsStats200 = {
  total_views: number;
  unique_visitors: number;
  popular_pages: GetAnalyticsStats200PopularPagesItem[];
  daily_stats: GetAnalyticsStats200DailyStatsItem[];
};

export type GetAnalyticsStats403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type GetAnalyticsPopularParams = {
  /**
   * Maximum number of pages to return
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
};

export type GetAnalyticsPopular200PopularPagesItem = {
  path: string;
  views: number;
};

export type GetAnalyticsPopular200 = {
  popular_pages: GetAnalyticsPopular200PopularPagesItem[];
};

export type GetAdminComments200CommentsItemParentId = string | null;

export type GetAdminComments200CommentsItem = {
  id: string;
  post_slug: string;
  user_id: string;
  parent_id: GetAdminComments200CommentsItemParentId;
  content: string;
  status: string;
  likes_count: number;
  created_at: number;
  updated_at: number;
  username: string;
};

export type GetAdminComments200 = {
  comments: GetAdminComments200CommentsItem[];
};

export type GetAdminComments403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

/**
 * New comment status
 */
export type PutAdminCommentStatusBodyStatus =
  (typeof PutAdminCommentStatusBodyStatus)[keyof typeof PutAdminCommentStatusBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutAdminCommentStatusBodyStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const;

export type PutAdminCommentStatusBody = {
  /** New comment status */
  status: PutAdminCommentStatusBodyStatus;
};

export type PutAdminCommentStatus200 = {
  message: string;
};

export type PutAdminCommentStatus400 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PutAdminCommentStatus403 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};

export type PutAdminCommentStatus404 = {
  error: string;
  message: string;
  status: number;
  details?: unknown;
};
