/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteCommentsDelete200,
  GetCommentsList200,
  GetCommentsListParams,
  PostCommentsCreate201,
  PostCommentsCreateBody,
  PostCommentsLike200,
  PutCommentsUpdate200,
  PutCommentsUpdateBody,
} from '../playgroundAPI.schemas';

import { customAxios } from '../../axios-instance';

export const getComments = () => {
  /**
   * Get all approved comments for a blog post with nested replies
   * @summary List comments
   */
  const getCommentsList = (postSlug: string, params?: GetCommentsListParams) => {
    return customAxios<GetCommentsList200>({ url: `/api/comments/${postSlug}`, method: 'GET', params });
  };
  /**
   * Post a new comment or reply to an existing comment
   * @summary Create comment
   */
  const postCommentsCreate = (postCommentsCreateBody: PostCommentsCreateBody) => {
    return customAxios<PostCommentsCreate201>({
      url: `/api/comments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postCommentsCreateBody,
    });
  };
  /**
   * Edit your own comment (author or admin only)
   * @summary Update comment
   */
  const putCommentsUpdate = (id: string, putCommentsUpdateBody: PutCommentsUpdateBody) => {
    return customAxios<PutCommentsUpdate200>({
      url: `/api/comments/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putCommentsUpdateBody,
    });
  };
  /**
   * Delete your own comment (author or admin only)
   * @summary Delete comment
   */
  const deleteCommentsDelete = (id: string) => {
    return customAxios<DeleteCommentsDelete200>({ url: `/api/comments/${id}`, method: 'DELETE' });
  };
  /**
   * Toggle like status on a comment
   * @summary Like/unlike comment
   */
  const postCommentsLike = (id: string) => {
    return customAxios<PostCommentsLike200>({ url: `/api/comments/${id}/like`, method: 'POST' });
  };
  return { getCommentsList, postCommentsCreate, putCommentsUpdate, deleteCommentsDelete, postCommentsLike };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetCommentsListResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getComments>['getCommentsList']>>>;
export type PostCommentsCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getComments>['postCommentsCreate']>>
>;
export type PutCommentsUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getComments>['putCommentsUpdate']>>
>;
export type DeleteCommentsDeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getComments>['deleteCommentsDelete']>>
>;
export type PostCommentsLikeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getComments>['postCommentsLike']>>
>;
