/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Playground API
 * A full-featured backend API for static websites using Cloudflare Workers
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAdminComments200,
  PutAdminCommentStatus200,
  PutAdminCommentStatusBody,
} from '../playgroundAPI.schemas';

import { customAxios } from '../../axios-instance';

export const getAdmin = () => {
  /**
   * Get all pending comments that need moderation (admin only)
   * @summary Get pending comments
   */
  const getAdminComments = () => {
    return customAxios<GetAdminComments200>({ url: `/api/admin/comments`, method: 'GET' });
  };
  /**
   * Approve or reject a comment (admin only)
   * @summary Update comment status
   */
  const putAdminCommentStatus = (id: string, putAdminCommentStatusBody: PutAdminCommentStatusBody) => {
    return customAxios<PutAdminCommentStatus200>({
      url: `/api/admin/comments/${id}/status`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putAdminCommentStatusBody,
    });
  };
  return { getAdminComments, putAdminCommentStatus };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetAdminCommentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getAdminComments']>>>;
export type PutAdminCommentStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAdmin>['putAdminCommentStatus']>>
>;
