"use strict";
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
var __root_1 = require("./routes/__root");
var todo_1 = require("./routes/todo");
var showcase_1 = require("./routes/showcase");
var player_1 = require("./routes/player");
var about_1 = require("./routes/about");
var index_1 = require("./routes/index");
var TodoRoute = todo_1.Route.update({
    id: '/todo',
    path: '/todo',
    getParentRoute: function () { return __root_1.Route; },
});
var ShowcaseRoute = showcase_1.Route.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: function () { return __root_1.Route; },
});
var PlayerRoute = player_1.Route.update({
    id: '/player',
    path: '/player',
    getParentRoute: function () { return __root_1.Route; },
});
var AboutRoute = about_1.Route.update({
    id: '/about',
    path: '/about',
    getParentRoute: function () { return __root_1.Route; },
});
var IndexRoute = index_1.Route.update({
    id: '/',
    path: '/',
    getParentRoute: function () { return __root_1.Route; },
});
var rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    PlayerRoute: PlayerRoute,
    ShowcaseRoute: ShowcaseRoute,
    TodoRoute: TodoRoute,
};
exports.routeTree = __root_1.Route
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
